# Generated by Django 5.1.4 on 2025-04-07 06:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_name', models.CharField(blank=True, max_length=200, null=True)),
                ('team_name', models.CharField(blank=True, max_length=200, null=True)),
                ('event_details', models.TextField(blank=True, null=True)),
                ('start_date', models.DateTimeField(blank=True, null=True)),
                ('end_date', models.DateTimeField(blank=True, null=True)),
                ('event_video', models.FileField(blank=True, null=True, upload_to='event_video/')),
                ('event_image', models.ImageField(blank=True, null=True, upload_to='images/')),
                ('seat_avilability', models.IntegerField(blank=True, null=True)),
                ('venue', models.CharField(blank=True, max_length=100, null=True)),
                ('address', models.CharField(blank=True, max_length=500, null=True)),
            ],
        ),
    ]
