# Generated by Django 5.1.4 on 2025-04-08 10:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('amora_app', '0003_booking'),
    ]

    operations = [
        migrations.CreateModel(
            name='Gallery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_name', models.CharField(blank=True, max_length=100, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='images/')),
                ('review_video', models.FileField(blank=True, null=True, upload_to='review_videos/')),
                ('date', models.DateTimeField(blank=True, null=True)),
            ],
        ),
    ]
