# Generated by Django 5.1.4 on 2025-04-08 10:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('amora_app', '0004_gallery'),
    ]

    operations = [
        migrations.RenameField(
            model_name='gallery',
            old_name='review_video',
            new_name='event_video',
        ),
    ]
